CREATE TABLE stocks (
                        id SERIAL PRIMARY KEY,
                        symbol VARCHAR(255),
                        company_name VARCHAR(255),
                        primary_exchange VARCHAR(255),
                        calculation_price VARCHAR(255),
                        open DOUBLE PRECISION,
                        open_time BIGINT,
                        open_source VARCHAR(255),
                        close DOUBLE PRECISION,
                        close_time BIGINT,
                        close_source VARCHAR(255),
                        high DOUBLE PRECISION,
                        high_time BIGINT,
                        high_source VARCHAR(255),
                        low DOUBLE PRECISION,
                        low_time BIGINT,
                        low_source VARCHAR(255),
                        latest_price DOUBLE PRECISION,
                        latest_source VARCHAR(255),
                        latest_time VARCHAR(255),
                        latest_update BIGINT,
                        latest_volume BIGINT,
                        iex_realtime_price DOUBLE PRECISION,
                        iex_realtime_size INTEGER,
                        iex_last_updated BIGINT,
                        delayed_price DOUBLE PRECISION,
                        delayed_price_time BIGINT,
                        odd_lot_delayed_price DOUBLE PRECISION,
                        odd_lot_delayed_price_time BIGINT,
                        extended_price DOUBLE PRECISION,
                        extended_change DOUBLE PRECISION,
                        extended_change_percent DOUBLE PRECISION,
                        extended_price_time BIGINT,
                        previous_close DOUBLE PRECISION,
                        previous_volume BIGINT,
                        change DOUBLE PRECISION,
                        change_percent DOUBLE PRECISION,
                        volume BIGINT,
                        iex_market_percent DOUBLE PRECISION,
                        iex_volume BIGINT,
                        iex_bid_price DOUBLE PRECISION,
                        iex_bid_size INTEGER,
                        iex_ask_price DOUBLE PRECISION,
                        iex_ask_size INTEGER,
                        iex_open DOUBLE PRECISION,
                        iex_open_time BIGINT,
                        iex_close DOUBLE PRECISION,
                        iex_close_time BIGINT,
                        market_cap BIGINT,
                        pe_ratio DOUBLE PRECISION,
                        week52_high DOUBLE PRECISION,
                        week52_low DOUBLE PRECISION,
                        ytd_change DOUBLE PRECISION,
                        last_trade_time BIGINT,
                        currency VARCHAR(255),
                        isusmarket_open BOOLEAN
);